version: "3.9"
services:
  postgres16:
    container_name: postgres16
    image: postgres:16-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: sasa
      POSTGRES_DB: msvc_usuarios
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring
  sql10:
    container_name: sql10
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1434:1433"
    environment:
      MSSQL_SA_PASSWORD: r00t.R00T
      ACCEPT_EULA: "Y"
    volumes:
      - data-sql:/var/opt/mssql/data
    restart: always
    networks:
      - spring
    user: "0:0"

  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msvc_habitaciones
    volumes:
      - data-mysql2:/var/lib/mysql
    restart: always
    networks:
      - spring
  mysql9:
    container_name: mysql9
    image: mysql:8
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msvc_tipos
    volumes:
      - data-mysql1:/var/lib/mysql
    restart: always
    networks:
      - spring

  msvc-usuarios:
    container_name: msvc-usuarios
    image: diego0012231/usuarios:latest
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      DB_HOST: postgres16:5432
      DB_DATABASE: msvc_usuarios
      DB_USERNAME: postgres
      DB_PASSWORD: sasa
    networks:
      - spring
    restart: always

  msvc-reservas:
    container_name: msvc-reservas
    image: diego0012231/reservas:latest
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      DB_HOST: sql10:1433
      DB_DATABASE: msvc_reservas
      DB_USERNAME: sa
      DB_PASSWORD: r00t.R00T
    networks:
      - spring
    restart: always

  msvc-habitaciones:
    container_name: msvc-habitaciones
    image: diego0012231/habitaciones:latest
    ports:
      - "8003:8003"
    environment:
      PORT: 8003
      DB_HOST: mysql8:3306
      DB_DATABASE: msvc_habitaciones
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - spring
    restart: always

  msvc-tipos:
      container_name: msvc-tipos
      image: diego0012231/tipos:latest
      ports:
        - "8004:8004"
      environment:
        PORT: 8004
        DB_HOST: mysql9:3306
        DB_DATABASE: msvc_tipos
        DB_USERNAME: root
        DB_PASSWORD: root
      networks:
        - spring
      restart: always

volumes:
  data-postgres:
    name: data-postgres
  data-sql:
    name: data-sql
  data-mysql2:
    name: data-mysql2
  data-mysql1:
    name: data-mysql1

networks:
  spring:
